<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class NewsController extends Controller
{
    private function mapNewsItem($row)
    {
        // Handle CLOB data type for Oracle news descriptions
        $content = '';

        $description = $row->news_description ?? $row->NEWS_DESCRIPTION ?? null;

        if ($description) {
            if (is_resource($description)) {
                $content = stream_get_contents($description);
            } else {
                $content = (string) $description;
            }
        }

        $dateStr = 'N/A';

        $date = $row->date ?? $row->DATE ?? null;

        if ($date) {
            $dateStr = date('F j, Y', strtotime($date));
        }

        return [
            'id' => $row->id ?? $row->ID,
            'title' => $row->news_title ?? $row->NEWS_TITLE,
            'content' => $content,
            'author' => $row->author_name ?? $row->AUTHOR_NAME,
            'channel' => $row->category ?? $row->CATEGORY,
            'date' => $dateStr,
            'image' => $row->image ?? $row->IMAGE ?? '',
            'status' => $row->status ?? $row->STATUS ?? 'Draft',
            'comments' => []
        ];
    }

    public function index()
    {
        if (!session('user_logged_in')) {
            return redirect('/login')->with('error', 'Please login to view news.');
        }

        // Query published news from Oracle table using uppercase table name
        $newsRows = DB::select("
    SELECT *
    FROM NEWS_ITEMS
    WHERE LOWER(STATUS)='published'
    ORDER BY ID DESC
");

        $newsList = [];
        foreach ($newsRows as $row) {
            $newsList[] = $this->mapNewsItem($row);
        }

        return view('news.index', ['newsList' => $newsList]);
    }

    public function show($id)
    {
        if (!session('user_logged_in')) {
            return redirect('/login')->with('error', 'Please login to view news.');
        }

        // Fetch news article by ID
        $newsRow = DB::select(
            "SELECT * FROM NEWS_ITEMS WHERE ID = ?",
            [$id]
        );

        $newsRow = $newsRow[0] ?? null;

        if (!$newsRow) {
            return redirect('/home')->with('error', 'News article not found.');
        }

        $news = $this->mapNewsItem($newsRow);

        // Fetch comments for this article
        $commentRows = DB::select(
            "SELECT * FROM COMMENTS
     WHERE ARTICLE_ID=?
     ORDER BY ID ASC",
            [$id]
        );

        foreach ($commentRows as $cRow) {
            $news['comments'][] = [
                'user' => $cRow->user_name ?? $cRow->USER_NAME,
                'text' => $cRow->comment_text ?? $cRow->COMMENT_TEXT,
                'date' => $cRow->date ?? $cRow->DATE
            ];
        }

        return view('news.show', ['news' => $news]);
    }

    public function create()
    {
        $role = strtolower(session('user_role'));
        if (!session('user_logged_in') || $role === 'reader') {
            return redirect('/home')->with('error', 'You do not have permission to write news.');
        }

        return view('news.create');
    }

    public function store(Request $request)
    {
        $role = strtolower(session('user_role'));
        if (!session('user_logged_in') || $role === 'reader') {
            return redirect('/home')->with('error', 'You do not have permission to write news.');
        }

        $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
            'category' => 'required|string|max:50'
        ]);

        // Insert news item as Draft. ID is generated by trigger NEWS_ITEMS_TRG.
        DB::statement(
            "
INSERT INTO NEWS_ITEMS
(
NEWS_TITLE,
AUTHOR_NAME,
NEWS_DESCRIPTION,
CATEGORY,
STATUS,
DATE,
IMAGE
)
VALUES
(
?,
?,
?,
?,
?,
SYSDATE,
?
)
",
            [
                $request->input('title'),
                session('user_name', 'Anonymous Writer'),
                $request->input('content'),
                $request->input('category'),
                'Draft',
                null
            ]
        );

        return redirect('/author/dashboard')->with('success', "Your dispatch '{$request->title}' was successfully saved as a draft!");
    }

    public function storeComment(Request $request, $id)
    {
        if (!session('user_logged_in')) {
            return redirect('/login');
        }

        $request->validate([
            'comment' => 'required|string|max:4000'
        ]);

        // Insert comment. ID is generated by trigger COMMENTS_BIR.
        DB::statement(
            "
INSERT INTO COMMENTS
(
ARTICLE_ID,
USER_NAME,
COMMENT_TEXT,
STATUS,
DATE
)
VALUES
(
?,
?,
?,
?,
SYSDATE
)
",
            [
                $id,
                session('user_name', 'Anonymous Reader'),
                $request->input('comment'),
                'Approved'
            ]
        );

        return redirect()->back()->with('success', 'Your letter was added successfully!');
    }

    // Admin Dashboard Logic
    public function adminDashboard()
    {
        $totalArticles = DB::selectOne("SELECT COUNT(*) TOTAL FROM NEWS_ITEMS")->total;

        $totalUsers = DB::selectOne("SELECT COUNT(*) TOTAL FROM USERS")->total;

        $totalComments = DB::selectOne("SELECT COUNT(*) TOTAL FROM COMMENTS")->total;

        // Retrieve all articles (draft and published)
        $allNewsRows = DB::select("
SELECT *
FROM NEWS_ITEMS
ORDER BY ID DESC
");

        $newsList = [];
        foreach ($allNewsRows as $row) {
            $newsList[] = $this->mapNewsItem($row);
        }

        // Retrieve audit logs populated by the NEWS_PUBLISH_TRG database trigger
        $auditLogs = DB::select("
SELECT *
FROM AUDIT_LOGS
ORDER BY CREATED_AT DESC
FETCH FIRST 10 ROWS ONLY
");

        return view('admin.dashboard', [
            'totalArticles' => $totalArticles,
            'totalUsers' => $totalUsers,
            'totalComments' => $totalComments,
            'newsList' => $newsList,
            'auditLogs' => $auditLogs
        ]);
    }

    // Stored Procedure and Transaction execution for publishing news
    public function publishNews($id)
    {
        DB::transaction(function () use ($id) {
            // Execute the Oracle stored procedure publish_news_proc
            DB::statement("BEGIN publish_news_proc(?); END;", [$id]);
        });

        return redirect()->back()->with('success', 'Dispatch successfully published via Oracle Stored Procedure!');
    }

    // Author Dashboard Logic
    public function authorDashboard()
    {
        $authorName = session('user_name');

        // Fetch news written by this author
        $authorNewsRows = DB::select(
            "
SELECT *
FROM NEWS_ITEMS
WHERE LOWER(AUTHOR_NAME)=?
ORDER BY ID DESC
",
            [
                strtolower($authorName)
            ]
        );

        $newsList = [];
        foreach ($authorNewsRows as $row) {
            $newsList[] = $this->mapNewsItem($row);
        }

        return view('author.dashboard', [
            'newsList' => $newsList
        ]);
    }

    // Admin action to delete an article
    public function deleteNews($id)
    {
        DB::statement(
            "DELETE FROM NEWS_ITEMS WHERE ID=?",
            [$id]
        );
        return redirect()->back()->with('success', 'Article deleted from archives.');
    }
}
