<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class NewsController extends Controller
{
    private function mapNewsItem($row)
    {
        // Handle CLOB data type for Oracle news descriptions
        $content = '';
        if (isset($row->news_description)) {
            if (is_resource($row->news_description)) {
                $content = stream_get_contents($row->news_description);
            } else {
                $content = (string)$row->news_description;
            }
        }

        // Format dates consistently
        $dateStr = 'N/A';
        if (!empty($row->date)) {
            $dateStr = date('F j, Y', strtotime($row->date));
        }

        return [
            'id' => $row->id,
            'title' => $row->news_title,
            'content' => $content,
            'author' => $row->author_name,
            'channel' => $row->category,
            'date' => $dateStr,
            'image' => $row->image ?? '',
            'status' => $row->status ?? 'Draft',
            'comments' => []
        ];
    }

    public function index()
    {
        if (!session('user_logged_in')) {
            return redirect('/login')->with('error', 'Please login to view news.');
        }

        // Query published news from Oracle table using uppercase table name
        $newsRows = DB::table('NEWS_ITEMS')
            ->where(DB::raw('LOWER(status)'), 'published')
            ->orderBy('id', 'desc')
            ->get();

        $newsList = [];
        foreach ($newsRows as $row) {
            $newsList[] = $this->mapNewsItem($row);
        }

        return view('news.index', ['newsList' => $newsList]);
    }

    public function show($id)
    {
        if (!session('user_logged_in')) {
            return redirect('/login')->with('error', 'Please login to view news.');
        }

        // Fetch news article by ID
        $newsRow = DB::table('NEWS_ITEMS')->where('id', $id)->first();

        if (!$newsRow) {
            return redirect('/home')->with('error', 'News article not found.');
        }

        $news = $this->mapNewsItem($newsRow);

        // Fetch comments for this article
        $commentRows = DB::table('COMMENTS')
            ->where('article_id', $id)
            ->orderBy('id', 'asc')
            ->get();

        foreach ($commentRows as $cRow) {
            $news['comments'][] = [
                'user' => $cRow->user_name,
                'text' => $cRow->comment_text,
                'date' => $cRow->date
            ];
        }

        return view('news.show', ['news' => $news]);
    }

    public function create()
    {
        $role = strtolower(session('user_role'));
        if (!session('user_logged_in') || $role === 'reader') {
            return redirect('/home')->with('error', 'You do not have permission to write news.');
        }

        return view('news.create');
    }

    public function store(Request $request)
    {
        $role = strtolower(session('user_role'));
        if (!session('user_logged_in') || $role === 'reader') {
            return redirect('/home')->with('error', 'You do not have permission to write news.');
        }

        $request->validate([
            'title' => 'required|string|max:255',
            'content' => 'required|string',
            'category' => 'required|string|max:50'
        ]);

        // Insert news item as Draft. ID is generated by trigger NEWS_ITEMS_TRG.
        DB::table('NEWS_ITEMS')->insert([
            'news_title' => $request->title,
            'author_name' => session('user_name', 'Anonymous Writer'),
            'news_description' => $request->content,
            'category' => $request->category,
            'status' => 'Draft',
            'date' => DB::raw('SYSDATE'),
            'image' => null
        ]);

        return redirect('/author/dashboard')->with('success', "Your dispatch '{$request->title}' was successfully saved as a draft!");
    }

    public function storeComment(Request $request, $id)
    {
        if (!session('user_logged_in')) {
            return redirect('/login');
        }

        $request->validate([
            'comment' => 'required|string|max:4000'
        ]);

        // Insert comment. ID is generated by trigger COMMENTS_BIR.
        DB::table('COMMENTS')->insert([
            'article_id' => $id,
            'user_name' => session('user_name', 'Anonymous Reader'),
            'comment_text' => $request->comment,
            'status' => 'Approved',
            'date' => DB::raw('SYSDATE')
        ]);

        return redirect()->back()->with('success', 'Your letter was added successfully!');
    }

    // Admin Dashboard Logic
    public function adminDashboard()
    {
        $totalArticles = DB::table('NEWS_ITEMS')->count();
        $totalUsers = DB::table('USERS')->count();
        $totalComments = DB::table('COMMENTS')->count();

        // Retrieve all articles (draft and published)
        $allNewsRows = DB::table('NEWS_ITEMS')
            ->orderBy('id', 'desc')
            ->get();

        $newsList = [];
        foreach ($allNewsRows as $row) {
            $newsList[] = $this->mapNewsItem($row);
        }

        // Retrieve audit logs populated by the NEWS_PUBLISH_TRG database trigger
        $auditLogs = DB::table('AUDIT_LOGS')
            ->orderBy('created_at', 'desc')
            ->take(10)
            ->get();

        return view('admin.dashboard', [
            'totalArticles' => $totalArticles,
            'totalUsers' => $totalUsers,
            'totalComments' => $totalComments,
            'newsList' => $newsList,
            'auditLogs' => $auditLogs
        ]);
    }

    // Stored Procedure and Transaction execution for publishing news
    public function publishNews($id)
    {
        DB::transaction(function() use ($id) {
            // Execute the Oracle stored procedure publish_news_proc
            DB::statement("BEGIN publish_news_proc(?); END;", [$id]);
        });

        return redirect()->back()->with('success', 'Dispatch successfully published via Oracle Stored Procedure!');
    }

    // Author Dashboard Logic
    public function authorDashboard()
    {
        $authorName = session('user_name');

        // Fetch news written by this author
        $authorNewsRows = DB::table('NEWS_ITEMS')
            ->where(DB::raw('LOWER(author_name)'), strtolower($authorName))
            ->orderBy('id', 'desc')
            ->get();

        $newsList = [];
        foreach ($authorNewsRows as $row) {
            $newsList[] = $this->mapNewsItem($row);
        }

        return view('author.dashboard', [
            'newsList' => $newsList
        ]);
    }

    // Admin action to delete an article
    public function deleteNews($id)
    {
        DB::table('NEWS_ITEMS')->where('id', $id)->delete();
        return redirect()->back()->with('success', 'Article deleted from archives.');
    }
}
